### ISSUE TITLE
Job needs restart

### ISSUE THREAD

**Issue by mfansler** [conda-forge/sqlite-feedstock#110]
@ocefpaf one of the build jobs on Travis CI failed to start: https://app.travis-ci.com/github/conda-forge/sqlite-feedstock/jobs/622764435. Someone with permissions needs to restart it.

**Comment by ocefpaf** [comment]
Restarted it. Let's close this when the job is done. Thanks for ping!

**Comment by mfansler** [comment]
Confirmed the missing build is now uploaded. Thanks!
