### ISSUE TITLE
Update to version 3.28.0

### ISSUE THREAD

**Issue by sangramga** [conda-forge/sqlite-feedstock#44]
Find the security vulnerabilities in sqlite 3.26.0, 3.27.0
[https://www.cvedetails.com/vulnerability-list/vendor_id-9237/year-2019/Sqlite.html](https://www.cvedetails.com/vulnerability-list/vendor_id-9237/year-2019/Sqlite.html)

So requesting to upgrade to 3.28.0

**Comment by ocefpaf** [comment]
@conda-forge-bot the bot missed the auto-update here. Maybe the URL changed.

BTW, do you want to send a PR? It should be just adding the new version and updating the checksum.
