### ISSUE TITLE
Latest build needs to be rerun

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/sqlite-feedstock#61]
![image](https://user-images.githubusercontent.com/90008/112146294-c83f5c80-8bb1-11eb-9db7-d53c9a8e40e5.png)

missing results for linux platforms is due to quai failure yesterday

**Comment by xylar** [comment]
@hmaarrfk, I was able to restart CI on most of the failed runs but not Drone.  But I went ahead and made a dummy commit that should re-trigger everything: https://github.com/conda-forge/sqlite-feedstock/commit/049f12913abf532725ebdd83c09211a1917f83ce

Keep an eye on that and close this if/when it's successful.

**Comment by ocefpaf** [comment]
Looks like it worked. Thanks @xylar! FYI more updates that for merge during the quay.io outage may need restart. So keep that in mind when you find something that is missing from yesterday.
